In [1]:
import numpy as np

#### Stacking of Array
- Cannot be done on the matrix
- only done on array 1D arrays

In [6]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

In [7]:
np.vstack((A, B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.hstack((A, B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.column_stack((A, B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Spliting Arrays

In [12]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [18]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

#### Searching in Array

In [17]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [18]:
x = np.where(arr == 4)
x

(array([3, 5, 6]),)

In [26]:
arr = [6, 7, 8, 9]
x = np.searchsorted(arr, 7)
y = np.searchsorted(arr, 7, side="right")
print(x)
print(y)
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
x

1
2


array([1, 2, 3])

In [27]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])

In [28]:
arr = np.array([[4, 5, 6, 3], [6, 4, 3, 2]])
np.sort(arr)


array([[3, 4, 5, 6],
       [2, 3, 4, 6]])