In [2]:
import numpy as np

## Numpy Indexing and Slicing of Vectors

In [4]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[7]

np.int64(18)

In [8]:
arr[6]

np.int64(17)

In [12]:
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[::2]

array([11, 13, 15, 17, 19])

In [7]:
arr[1::2]

array([12, 14, 16, 18, 20])

In [8]:
arr[1:5:2]

array([12, 14])

In [13]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[:2]

array([11, 12])

In [16]:
arr[2:8:2]

array([13, 15, 17])

#### Boolean Indexing

In [9]:
arr[arr > 15] 

array([16, 17, 18, 19, 20])

In [10]:
arr[arr % 2 == 0]

array([12, 14, 16, 18, 20])

In [11]:
arr[(arr%2 == 0) & (arr > 15)]

array([16, 18, 20])

In [12]:
arr[(arr%2 == 0) | (arr > 15)]

array([12, 14, 16, 17, 18, 19, 20])

In [13]:
arr[~(arr > 15)]

array([11, 12, 13, 14, 15])

In [16]:
mask = (arr%2==0) & (arr < 15)
arr[mask]

array([12, 14])

#### Fancy Indexing

In [18]:
arr[[1, 3, 5]]

array([12, 14, 16])

In [23]:
arr[np.where(arr < 14)]

array([11, 12, 13])

In [25]:
arr[5] = 20
arr

array([11, 12, 13, 14, 15, 20, 17, 18, 19, 20])

In [32]:
arr[1:4] = 50
arr

array([11, 50, 50, 50, 30, 20, 17, 18, 30, 20])

In [30]:
arr[[1,4, 3, 8]] = 30
arr

array([11, 30, 13, 30, 30, 20, 17, 18, 30, 20])

### Numpy Indexing & Slicing - MATRIX

In [34]:
arr = np.arange(1, 30+1).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr[5] #Single for rows

array([26, 27, 28, 29, 30])

In [45]:
arr[1,2]  #accesing first element 1st row & first column

np.int64(8)

In [27]:
arr[5,4]

np.int64(30)

In [46]:
arr[1, :]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[:, 1]

array([ 2,  7, 12, 17, 22, 27])

In [48]:
s = arr[0:2, 1:3]
s

array([[2, 3],
       [7, 8]])

In [32]:
arr[3:6, 3:5] # or arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [35]:
arr[:,3] #Accessing Column

array([ 4,  9, 14, 19, 24, 29])

In [49]:
arr[[0,2],[1, 2]]

array([ 2, 13])

### Boolean Indexing

In [38]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
bool_index = arr % 2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [44]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])