### Array Operations

In [7]:
import numpy as np

In [8]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [9]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [10]:
arr2 - arr1

array([5, 5, 5, 5, 5])

In [11]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [12]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [18]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [21]:
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr2 + 100

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125]])

### BroadCasting

In [16]:
l = [10,20,30,40]
arr = np.array(l)

In [17]:
arr + 10

array([20, 30, 40, 50])

### Deep and Shallow Copy

In [37]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
sli = a[:5]
sli * 10

array([10, 20, 30, 40, 50])

In [39]:
a[4:6] * 10

array([50, 60])

In [40]:
b = a.copy()

In [41]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
b[0] = 11

In [43]:
b

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])