In [2]:
import numpy as np

## Numpy Indexing and Slicing of Vectors

In [5]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[7]

np.int64(18)

In [8]:
arr[6]

np.int64(17)

In [12]:
arr[1:5]

array([12, 13, 14, 15])

In [13]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[:2]

array([11, 12])

In [16]:
arr[2:8:2]

array([13, 15, 17])

### Numpy Indexing & Slicing - MATRIX

In [20]:
arr = np.arange(1, 30+1).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr[5] #Single for rowsS

array([26, 27, 28, 29, 30])

In [26]:
arr[0,0] #accesing first element 1st row & first column

np.int64(1)

In [27]:
arr[5,4]

np.int64(30)

In [30]:
s = arr[0:2, 1:3]
s

array([[2, 3],
       [7, 8]])

In [32]:
arr[3:6, 3:5] # or arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [35]:
arr[:,3] #Accessing Column

array([ 4,  9, 14, 19, 24, 29])

### Boolean Indexing

In [38]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
bool_index = arr % 2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [44]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])