In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [4]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
A * B #Wrong

array([[ 5, 12],
       [21, 32]])

In [6]:
A @ B #Right

array([[19, 22],
       [43, 50]])

In [7]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
A.T

array([[1, 3],
       [2, 4]])