<p>NumPy (short for Numerical Python) is the fundamental open-source library for scientific computing in Python.<br/>
All NumPy arrays are homogeneous (elements of the same data type) and support efficient operations.</p>
<p>Arrays can be of type :- <br/>
<ul>
    <li>1D Array</li>
     <li>Multi-dimentional Array</li>
</ul></p>

In [2]:
import numpy as np

<p>Giving alias to the numpy for easy use</p>

In [9]:
print(np.__version__)

2.3.5


<h4>Array Creation</h4>

<p>To create an array using numpy we can use .array method provided by numpy</p>

<ul>
  <li><strong>Data vs Shape:</strong> Use <code>[]</code> when passing existing data and <code>()</code> when specifying the shape of the array.</li>
  <li><strong>Nested Lists Define Dimensions:</strong> Each level of list nesting represents one additional dimension in the array.</li>
  <li><strong>Single Data Type Rule:</strong> A NumPy array holds only one data type; mixed types are automatically promoted.</li>
  <li><strong>Consistent Shape Required:</strong> All rows and columns must have the same length; jagged structures are not allowed.</li>
  <li><strong>Shape Must Be a Tuple:</strong> Array dimensions are always provided as a tuple, even for one-dimensional arrays.</li>
  <li><strong>Generate When Possible:</strong> Prefer NumPy’s generator functions over converting Python iterables for better performance.</li>
  <li><strong>Explicit dtype for Control:</strong> Always specify <code>dtype</code> when precision, memory, or speed matters.</li>
  <li><strong>Zero-Based Indexing:</strong> NumPy arrays always start indexing from zero.</li>

</ul>


In [10]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


<h6>1D Array</h6>

In [11]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array(["S", 2, 3, 4, 5, 5])
print(arr1)
print(arr2)

[1 2 3 4 5 6]
['S' '2' '3' '4' '5' '5']


<p>when we try to add diffrent type of data in array , NumPy automatically converts all elements to a single, common format (dtype) when an array is created.</p>

<h6>Multi-dimentional Array</h6>

In [19]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [6, 7 , 8]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
arr3D = np.array([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])
print(arr3D)

In [2]:
arr4 = np.array([
    [
        [1, 2, 3],
        [2, 3, 4],
        [2, 3, 4],
    ],
    [
        [1, 2, 3],
        [2, 3, 4],
        [2, 3, 4],
    ]
])
print(arr4)

[[[1 2 3]
  [2 3 4]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]
  [2 3 4]]]


<h4>Accessing Array Elements</h4>

In [28]:
print(arr1[1])
print(arr2D[1][1])
print(arr3D[0][1])

2
5
[1 2 3 4]


<h4>Array Generation Functions</h4>

<p>Range Based Generation</p>

1. Arange - np.arange(start, stop, step) - It create an array in perticular range

In [4]:
arr5 = np.arange(1, 20, 2)
print(arr5)

[ 1  3  5  7  9 11 13 15 17 19]


2. Linspace - np.linspace(start, stop, num) - It returns evenly placed numbers in a range. We have to pass the countnumbers you want in range

In [6]:
arr6 = np.linspace(10, 20, 20)
print(arr6)

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


In [8]:
print(np.linspace(10, 5))#Default = 50

[10.          9.89795918  9.79591837  9.69387755  9.59183673  9.48979592
  9.3877551   9.28571429  9.18367347  9.08163265  8.97959184  8.87755102
  8.7755102   8.67346939  8.57142857  8.46938776  8.36734694  8.26530612
  8.16326531  8.06122449  7.95918367  7.85714286  7.75510204  7.65306122
  7.55102041  7.44897959  7.34693878  7.24489796  7.14285714  7.04081633
  6.93877551  6.83673469  6.73469388  6.63265306  6.53061224  6.42857143
  6.32653061  6.2244898   6.12244898  6.02040816  5.91836735  5.81632653
  5.71428571  5.6122449   5.51020408  5.40816327  5.30612245  5.20408163
  5.10204082  5.        ]


In [14]:
print(np.linspace(1, 5, 10, dtype=int))

[1 1 1 2 2 3 3 4 4 5]


<p>Zeros Array</p> - np.zeros((m, n)) return an m*n matrix with 0 values we can also specify datatype of zeros using <strong>dtype=datatype</strong>

In [16]:
zArray = np.zeros((2, 3), dtype=int)
print(zArray)

[[0 0 0]
 [0 0 0]]


<p>Ones Array</p>

In [17]:
oArray = np.ones((3, 4), dtype=int)
print(oArray)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


<p>Constant Array</p> - np.full((m, n), value) cretes an array with given valus . Same like zeros and one but value is provided by the user for the array . By default datatype is Integer

In [23]:
uArray = np.full((4, 5), 2, dtype=float)
print(uArray)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


<p>Empty Array</p> - np.empty((m, n)) used to initialize an  array with garbage values for further process.

In [25]:
eArray = np.empty((3, 4))
print(eArray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<p>Identity/Diagonal</p> - np.identity() or np.eye() All element of the digonal are 1 and others are set to 0 

In [17]:
eArray = np.identity(2, dtype=int)
print(eArray)

[[1 0]
 [0 1]]


In [29]:
eyeArray = np.eye(3,4)
print(eyeArray)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
