In [3]:
import numpy as np

In [6]:
np.random.rand(10) #gives values from -1 to 1

array([0.96255792, 0.40107841, 0.37640587, 0.39474302, 0.04366419,
       0.93468849, 0.40524768, 0.83105942, 0.38994869, 0.44106307])

In [13]:
np.random.randn(10)

array([ 0.20670737, -0.82375491,  0.55596426, -0.08082204, -0.69305507,
       -0.35131101,  0.60403419,  0.86474991,  0.125866  , -2.13778015])

In [16]:
np.random.randint(10 , 30, 7)

array([26, 26, 26, 17, 20, 10, 28], dtype=int32)