In [6]:
import numpy as np
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
arr3d[1, 0, 1]

np.int64(6)

In [7]:
print(arr3d[0])

[[1 2]
 [3 4]]


In [9]:
arr=np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])


In [11]:
arr[0]

array([[1, 2],
       [3, 4]])

In [12]:
arr[1:]

array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
arr[:, 0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [16]:
arr[:, :,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [17]:
arr[:, :]

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
arr[:, 0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
arr[1]

array([[5, 6],
       [7, 8]])

In [20]:
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [22]:
arr3d.sum(axis=2)

array([[ 3,  7],
       [11, 15]])